common_configs:
  experiment_name: quirk
  artifact_directory: artifacts/Lambda500_pre_selection_quirk
  gpus: 1
  clear_directories: True

metric_learning_configs:
  # Dataset parameters
  input_dir: Tracks_output
  output_dir: quickstart_metric_learning_processed
  pt_signal_cut: 0.
  pt_background_cut: 0.
  train_split: [800, 100, 100] # Number of [training, validation, testing] examples  (71,8,8) for lambda100
  true_edges: modulewise_true_edges

  # Model parameters
  spatial_channels: 3
  cell_channels: 0
  emb_hidden: 1024
  nb_layer: 4
  emb_dim: 12
  activation: Tanh
  weight: 2
  randomisation: 2
  points_per_batch: 100000
  r_train: 0.1
  r_val: 0.1
  r_test: 0.1
  knn: 50
  warmup: 8
  margin: 0.1
  lr: 0.001
  factor: 0.7
  patience: 50
  regime: [rp, hnm, norm]
  max_epochs: 50

gnn_configs:
  # Dataset parameters
  input_dir: quickstart_metric_learning_processed
  output_dir: quickstart_gnn_processed
  edge_cut: 0.5
  pt_signal_min: 0.
  pt_background_min: 0.
  datatype_names: [train, val, test] # Which directory prefixes to use, assuming at least a train dataset 
  datatype_split: [800, 100, 100]# Number of [training, validation, testing] examples
  noise: False

  # Model parameters
  spatial_channels: 3
  cell_channels: 0
  hidden: 64 #128
  n_graph_iters: 8
  nb_node_layer: 3
  nb_edge_layer: 3
  layernorm: True
  aggregation: sum_max
  hidden_activation: SiLU
  weight: 1
  warmup: 20
  lr: 0.002
  factor: 0.7
  patience: 100
  truth_key: pid_signal
  regime: []
  mask_background: True
  max_epochs: 100

track_building_configs:
  score_cut: 0.9
  output_dir: quickstart_trackbuilding_processed

evaluation_configs:
  output_dir: quickstart_evaluation
  min_pt: 0
  max_eta: 4
  min_track_length: 5
  min_particle_length: 7
  matching_fraction: 0.5
  matching_style: two_way
