python Examples/QuirkTracking/Scripts/Step_1_Train_Metric_Learning.py 
python Examples/QuirkTracking/Scripts/Step_2_Run_Metric_Learning.py 
python Examples/QuirkTracking/Scripts/Step_3_Train_GNN.py 
python Examples/QuirkTracking/Scripts/Step_4_Run_GNN.py
python Examples/QuirkTracking/Scripts/Step_5_Build_Track_Candidates.py
python Examples/QuirkTracking/Scripts/Step_6_Evaluate_Reconstruction.py